In [1]:
import cv2
print (cv2.__version__)

4.2.0


In [8]:
lastXzumiGelb=[]
collectXzumiGelb=[]
lastXTankGelb=[]
collectXTankGelb=[]
lastX=[]
collectX=[]
streeta = [158,134,13,167, 
             350,158,164,123,
             311,114,432,151,
             407,110,514,146,
             497,104,574,143,
             567,98,639,138,
             46,168,21,444,
             49,287,199,317,
             165,159,202,469,
             48,443,317,469,
             319,161,359,409,
             362,275,448,306,
             449,268,640,302,
             375,434,638,463,
             565,303,610,436]

def markZumiGelb(frame,coord):
    counter=0
    bol=False
    j=0
    for i in range(len(coord)-1):
        x = coord[i][0]
        y = coord[i+1][0]
        lastXzumiGelb=x
        x1=x[0]
        x2=x[1]
        y1=y[0]
        y2=y[1]
        if ((abs(x1-y1))<20) and ((abs(x2-y2))<20):
            counter=counter+1
        else:
            if (counter>40 and counter<70):
                lastXzumiGelb=x
                collectXzumiGelb.append(x)
                if(len(collectXzumiGelb)>20):
                    np.sort(collectXzumiGelb)
                    array = np.median(collectXzumiGelb, axis=0)
                    cv2.circle(frame, (int(array[0])-7,int(array[1])-7), 15, (255,0,0),2,8,0)
                else:
                    cv2.circle(frame, (x[0]-7,x[1]-7), 15, (255,0,0),2,8,0)
                bol=True
            counter=0
            #if(len(collectXzumiGelb)>200):
             #   collectXzumiGelb=collectXzumiGelb[1:]
                
    if(bol==False):
        if(len(collectXzumiGelb)>20):
            np.sort(collectXzumiGelb)
            arrays = np.median(collectXzumiGelb, axis=0)
            cv2.circle(frame, (int(arrays[0])-7,int(arrays[1])-7), 15, (255,0,0),2,8,0)
        else:
            cv2.circle(frame, (lastXzumiGelb[0]-7,lastXzumiGelb[1]-7), 15, (255,0,0),2,8,0)
        #if(len(collectXzumiGelb)>200):
                #collectXzumiGelb=collectXzumiGelb[1:]
    return frame

def markTankGelb(frame,coord):
    count=0
    j=0
    bol=False
    for i in range(len(coord)-1):
        x = coord[i][0]
        y = coord[i+1][0]
       
        x1=x[0]
        x2=x[1]
        y1=y[0]
        y2=y[1]
        if ((abs(x1-y1))<40) and ((abs(x2-y2))<40):
            count=count+1
        else:
            if (count>100):
                lastXTankGelb=x
                collectXTankGelb.append(x)
                if(len(collectXTankGelb)>20):
                    np.sort(collectXTankGelb)
                    array = np.median(collectXTankGelb, axis=0)
                    cv2.rectangle(frame,(int(array[0])-50,int(array[1])-60),(int(array[0])+10,int(array[1])+5),1,8,0)
                    putCoord(int(array[0])-50,int(array[1])-60,frame)
                else:
                    cv2.rectangle(frame,(int(x[0])-50,int(x[1])-60),(int(x[0])+10,int(x[1])+5),1,8,0)
                bol=True
            count=0   
    
        if(bol==False):
            if(len(collectXTankGelb)>20):
                np.sort(collectXTankGelb)
                array = np.median(collectXTankGelb, axis=0)
                putCoord(int(array[0])-50,int(array[1])-60,frame)
                cv2.rectangle(frame,(int(array[0])-50,int(array[1])-60),(int(array[0])+10,int(array[1])+5),1,8,0)
            else:
                cv2.rectangle(frame,(x[0]-50,x[1]-60),(x[0]+10,x[1]+5),1,8,0)
            #if(len(collectXTankGelb)>200):
                   # collectXTankGelb=collectXTankGelb[1:]
    
    return frame    

def putCoord(x,y,frame):
    newX=0
    newY=0
    array=lastX
    if len(collectX)>20:
        if array[0]>x:
            newX=x-array[0]
        if array[0]<x:
            newX=array[0]+x  
                             
        if array[1]>y:
            newY=array[1]+y
        if array[1]<y:
            newY=array[1]-y  
        c=str(newX)+","+str(newY)
        cv2.putText(frame, c, (x-15, y-15), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 0, 255), 2)
        return

def gencoordinates(x,y,frame):
    cv2.putText(frame, "0,0", (x-20, y+20), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 0, 255), 2)
    cv2.circle(frame, (x,y), 5, (255,0,0),10,8,0)
    cv2.line(frame, (x,0), (x,480), (255,0,0),1,8,0) 
    i = int(x/50)
    for j in range(i):
        cv2.putText(frame, "-"+str((j+1)*50), (x-((j+1)*50),y+20), cv2.FONT_HERSHEY_SIMPLEX, 0.2, (0, 0, 255), 1)
        cv2.circle(frame, (x-((j+1)*50),y), 1, (255,0,0),2,8,0)
    i = int(480-x/50)
    for j in range(i):
        cv2.putText(frame, ""+str((j+1)*50), (x+((j+1)*50),y+20), cv2.FONT_HERSHEY_SIMPLEX, 0.2, (0, 0, 255), 1)
        cv2.circle(frame, (x+((j+1)*50),y), 1, (255,0,0),2,8,0)
    i = int(y/50)
    for j in range(i):
        cv2.putText(frame, "-"+str((j+1)*50), (x-20,y+((j+1)*50)), cv2.FONT_HERSHEY_SIMPLEX, 0.2, (0, 0, 255), 1)
        cv2.circle(frame, (x,y-((j+1)*50)), 1, (255,0,0),2,8,0)
    i = int(640-y/50)
    for j in range(i):
        cv2.putText(frame, ""+str((j+1)*50), (x-20,y-((j+1)*50)), cv2.FONT_HERSHEY_SIMPLEX, 0.2, (0, 0, 255), 1)
        cv2.circle(frame, (x,y+((j+1)*50)), 1, (255,0,0),2,8,0)
   
    cv2.line(frame, (0,y), (640,y), (255,0,0),1,8,0) 
    return frame

def drawstreet(frame):
    for i in range(len(streeta)):
        if((i%4)==0):
            cv2.rectangle(frame,(streeta[i],streeta[i+1]),(streeta[i+2],streeta[i+3]),1,8,0)
    return frame

def calconstreet(frame):
    zumipos=lastXzumiGelb
    for i in range(len(streeta)):
        if((i%4)==0):
            if(zumipos[0]>streeta[i] and zumipos[0]<streeta[i+2]):
                if(zumipos[1]>streeta[i+1] and zumipos[1]<streeta[i+3]):
                    cv2.putText(frame, "onstreet", (zumipos[0]-20,zumipos[1]-20), cv2.FONT_HERSHEY_SIMPLEX, 0.2, (0, 0, 255), 1)
                    return frame
                
    cv2.putText(frame, "offroad", (zumipos[0]-20,zumipos[1]-20), cv2.FONT_HERSHEY_SIMPLEX, 0.2, (0, 0, 255), 1)
    return frame
                    
                    
                    
def findZeroPointer(coord,coord1):
    for i in range(len(coord)):
        for j in range(len(coord1)):
            x=coord[i][0]
            y=coord1[j][0]
            x1=x[0]
            x2=x[1]
            y1=y[0]
            y2=y[1]
            if ((abs(x1-y1))<7):
                if((abs(x2-y2))<7):
                    return x
    return "none"

def tracer():
    return

In [9]:
import cv2
import numpy as np


cap = cv2.VideoCapture('https://student:zumi2020@keuper-labs.org/zumi-cam')

    
while True:
    _, frame = cap.read()
    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    
    # Red color
    low_red = np.array([161, 185, 69])
    high_red = np.array([211, 255, 255])
    red_mask = cv2.inRange(hsv_frame, low_red, high_red)
    red = cv2.bitwise_and(frame, frame, mask=red_mask)
    
    # Blue color
    low_blue = np.array([80, 95, 120])
    high_blue = np.array([125, 185, 190])
    blue_mask = cv2.inRange(hsv_frame, low_blue, high_blue)
    blue = cv2.bitwise_and(frame, frame, mask=blue_mask)
    
    #Yellow
    low_yellow = np.array([21, 190, 100])
    high_yellow = np.array([32, 255, 255])
    yellow_mask = cv2.inRange(hsv_frame, low_yellow, high_yellow)
    yellow = cv2.bitwise_and(frame, frame, mask=yellow_mask)
   
    # Every color except white
    low = np.array([0, 42, 0])
    high = np.array([179, 255, 255])
    mask = cv2.inRange(hsv_frame, low, high)
    result = cv2.bitwise_and(frame, frame, mask=mask)
    coord1=cv2.findNonZero(red_mask)
    
    coord=cv2.findNonZero(blue_mask)
    
    x=findZeroPointer(coord,coord1)
    if(x != "none"):
        lastX=x
        collectX.append(x)
        if(len(collectX)>100):
            np.sort(collectX)
            array = np.median(collectX, axis=0)
            lastX=array
            frame = gencoordinates(int(array[0]+5),int(array[1]+5),frame)
            if(len(collectX)>200):
                collectX=collectX[1:]
        else:
            frame = gencoordinates(x[0]+5,x[1]+5,frame)
    if(x == "none"):
        if(len(collectX)>100):
            np.sort(collectX)
            array = np.median(collectX, axis=0)
            lastX=x
            frame = gencoordinates(int(array[0]+5),int(array[1]+5),frame)
            if(len(collectX)>200):
                collectX=collectX[1:]
        else:
            x=lastX
            frame = gencoordinates(x[0]+5,x[1]+5,frame)
    
    
    coord=cv2.findNonZero(yellow_mask)
    
    frame = markZumiGelb(frame,coord)
    frame = markTankGelb(frame,coord)
    cv2.imshow("Frame", frame)
    #cv2.imshow("Result", result)
    #cv2.imshow("Rot", blue)
    
    key = cv2.waitKey(1)
    if key == 27 & 0xff == ord('q'):
        break

IndexError: list index out of range

In [1]:
import cv2
import numpy as np

def nothing():
    return "none"
cv2.namedWindow("Trackbars")
cv2.createTrackbar("l-h", "Trackbars", 161,255,nothing)
cv2.createTrackbar("l-s", "Trackbars", 185,255,nothing)
cv2.createTrackbar("l-v", "Trackbars", 130,255,nothing)
cv2.createTrackbar("u-h", "Trackbars", 211,255,nothing)
cv2.createTrackbar("u-s", "Trackbars", 255,255,nothing)
cv2.createTrackbar("u-v", "Trackbars", 255,255,nothing)
cap = cv2.VideoCapture('https://student:zumi2020@keuper-labs.org/zumi-cam')
while True:
    frame = pic2
    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    l_h = cv2.getTrackbarPos("l-h", "Trackbars")
    l_s = cv2.getTrackbarPos("l-s", "Trackbars")
    l_v = cv2.getTrackbarPos("l-v", "Trackbars")
    u_h = cv2.getTrackbarPos("u-h", "Trackbars")
    u_s = cv2.getTrackbarPos("u-s", "Trackbars")
    u_v = cv2.getTrackbarPos("u-v", "Trackbars")
    lower_white = np.array([l_h,l_s,l_v], dtype=np.uint8)
    upper_white = np.array([u_h, u_s, u_v], dtype=np.uint8)
    mask = cv2.inRange(hsv_frame, lower_white, upper_white)

    res = cv2.bitwise_and(frame, frame, mask=mask)

    cv2.imshow("Result", res)
    #cv2.imshow("Result", frame)
    
    key = cv2.waitKey(1)
    if key == 27 & 0xff == ord('q'):
        break

NameError: name 'pic2' is not defined

In [ ]:
import numpy as np
a = np.array([[10, 1, 7], [3, 9, 11]])
a =np.sort(a)
np.median(a)
a.resize(5)
a[1:]
a=a[1:]
a

In [ ]:
lastXzumiGelb=[]
collectXzumiGelb=[]
lastXTankGelb=[]
collectXTankGelb=[]

In [4]:
def markZumiGelb(frame,coord):
    counter=0
    bol=False
    j=0
    for i in range(len(coord)-1):
        x = coord[i][0]
        y = coord[i+1][0]
        lastXzumiGelb=x
        x1=x[0]
        x2=x[1]
        y1=y[0]
        y2=y[1]
        if ((abs(x1-y1))<20) and ((abs(x2-y2))<20):
            counter=counter+1
        else:
            if (counter>60 and counter<80):
                lastXzumiGelb=x
                collectXzumiGelb.append(x)
                if(len(collectXzumiGelb)>20):
                    np.sort(collectXzumiGelb)
                    array = np.median(collectXzumiGelb, axis=0)
                    cv2.circle(frame, (int(array[0])-8,int(array[1])-8), 15, (255,0,0),2,8,0)
                else:
                    cv2.circle(frame, (x[0]-8,x[1]-8), 15, (255,0,0),2,8,0)
                bol=True
            counter=0
            #if(len(collectXzumiGelb)>200):
             #   collectXzumiGelb=collectXzumiGelb[1:]
                
    if(bol==False):
        if(len(collectXzumiGelb)>20):
            np.sort(collectXzumiGelb)
            arrays = np.median(collectXzumiGelb, axis=0)
            cv2.circle(frame, (int(arrays[0])-8,int(arrays[1])-8), 15, (255,0,0),2,8,0)
        else:
            cv2.circle(frame, (lastXzumiGelb[0]-8,lastXzumiGelb[1]-8), 15, (255,0,0),2,8,0)
        #if(len(collectXzumiGelb)>200):
                #collectXzumiGelb=collectXzumiGelb[1:]
    return frame
    

In [5]:
def markTankGelb(frame,coord):
    count=0
    j=0
    bol=False
    for i in range(len(coord)-1):
        x = coord[i][0]
        y = coord[i+1][0]
       
        x1=x[0]
        x2=x[1]
        y1=y[0]
        y2=y[1]
        if ((abs(x1-y1))<40) and ((abs(x2-y2))<40):
            count=count+1
        else:
            if (count>100):
                lastXTankGelb=x
                collectXTankGelb.append(x)
                if(len(collectXTankGelb)>20):
                    np.sort(collectXTankGelb)
                    array = np.median(collectXTankGelb, axis=0)
                    cv2.rectangle(frame,(int(array[0])-50,int(array[1])-60),(int(array[0])+10,int(array[1])+5),1,8,0)
                else:
                    cv2.rectangle(frame,(int(x[0])-50,int(x[1])-60),(int(x[0])+10,int(x[1])+5),1,8,0)
                bol=True
            count=0   
    
        if(bol==False):
            if(len(collectXTankGelb)>20):
                np.sort(collectXTankGelb)
                array = np.median(collectXTankGelb, axis=0)
                cv2.rectangle(frame,(int(array[0])-50,int(array[1])-60),(int(array[0])+10,int(array[1])+5),1,8,0)
            else:
                cv2.rectangle(frame,(x[0]-50,x[1]-60),(x[0]+10,x[1]+5),1,8,0)
            #if(len(collectXTankGelb)>200):
                   # collectXTankGelb=collectXTankGelb[1:]
    
    return frame

In [4]:
import cv2
import numpy as np

def nothing():
    return

cap = cv2.VideoCapture('https://student:zumi2020@keuper-labs.org/zumi-cam')
while True:
    _, frame = cap.read()
    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    low_yellow = np.array([21, 190, 100])
    high_yellow = np.array([32, 255, 255])
    yellow_mask = cv2.inRange(hsv_frame, low_yellow, high_yellow)
    yellow = cv2.bitwise_and(frame, frame, mask=yellow_mask)
    cv2.imshow("Result", yellow)
    
    coord=cv2.findNonZero(yellow_mask)
    
    frame = markZumiGelb(frame,coord)
    frame = markTankGelb(frame,coord)
    
    cv2.imshow("Result", yellow)
    cv2.imshow("Erg", frame)
    key = cv2.waitKey(1)
    if key == 27 & 0xff == ord('q'):
        break

error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [ ]:
from PIL import Image
import cv2
import numpy as np
# Gespeichertes Bild aus dem Zumi Stream
frame = cv2.imread("VideoCapture.jpg")
frame.shape
print(frame)
# coords  
streeta = [158,134,13,167, 
             350,158,164,123,
             311,114,432,151,
             407,110,514,146,
             497,104,574,143,
             567,98,639,138,
             46,168,21,444,
             49,287,199,317,
             165,159,202,469,
             48,443,317,469,
             319,161,359,409,
             362,275,448,306,
             449,268,640,302,
             375,434,638,463,
             565,303,610,436]

def drawstreet(frame):
    for i in range(len(streeta)):
        if((i%4)==0):
            cv2.rectangle(frame,(streeta[i],streeta[i+1]),(streeta[i+2],streeta[i+3]),(255,0,0),8,0)
            
            
drawstreet(frame)
cv2.imshow("Result", frame)
k = cv2.waitKey(0)

[[[ 31  36  51]
  [ 28  33  48]
  [ 24  29  44]
  ...
  [ 93  88  85]
  [ 94  90  89]
  [ 78  76  75]]

 [[ 31  36  51]
  [ 29  34  49]
  [ 24  29  44]
  ...
  [ 88  83  80]
  [ 91  87  86]
  [ 77  75  74]]

 [[ 30  35  50]
  [ 28  33  48]
  [ 24  29  44]
  ...
  [ 81  76  73]
  [ 88  84  83]
  [ 77  75  74]]

 ...

 [[102 124 149]
  [100 122 147]
  [ 89 112 134]
  ...
  [ 62  90  97]
  [ 62  90  97]
  [ 64  90  97]]

 [[ 86 108 133]
  [ 88 110 135]
  [ 83 106 128]
  ...
  [ 64  90  97]
  [ 66  89  97]
  [ 67  90  98]]

 [[ 62  84 109]
  [ 68  90 115]
  [ 68  91 113]
  ...
  [ 64  90  97]
  [ 68  89  97]
  [ 69  90  98]]]


In [7]:
import cv2
img = cv2.imread("VideoCapture.jpg")
cv2.imwrite("my.png",img)
cv2.imshow("lalala", img)
k = cv2.waitKey(0) # 0==wait forever

In [1]:
import cv2
import numpy as np
cap = cv2.VideoCapture('https://student:zumi2020@keuper-labs.org/zumi-cam')
while True:
    _, frame = cap.read()
    cv2.imshow("Frame", frame)
    key = cv2.waitKey(1)
    if key == 27 & 0xff == ord('q'):
        break


error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [3]:
from matplotlib import pyplot as plt
import numpy as np
import cv2
img = cv2.imread('https://student:zumi2020@keuper-labs.org/zumi-cam')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:376: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [17]:
import cv2

cap = cv2.VideoCapture('https://student:zumi2020@keuper-labs.org/zumi-cam')
ret,frame = cap.read() # return a single frame in variable `frame`
pic1 = frame
#cv2.imwrite("new1.png",pic1)

True

In [13]:
import cv2

cap = cv2.VideoCapture('https://student:zumi2020@keuper-labs.org/zumi-cam')
ret,frame = cap.read() 
pic1 = frame
#cv2.imwrite("my.png",pic2)

True

In [13]:
from PIL import Image
from numpy import asarray
import cv2
# load the image
image = Image.open('new1.png')
# convert image to numpy array
pic2 = asarray(image)
print(type(pic2))
# summarize shape
print(pic2.shape)

<class 'numpy.ndarray'>
(1080, 1440, 3)


In [5]:
from PIL import Image
from numpy import asarray
# load the image
image = Image.open('mynew.png')
# convert image to numpy array
pic1 = asarray(image)
print(type(pic2))
# summarize shape
print(pic1.shape)

<class 'numpy.ndarray'>
(1080, 1440, 3)


In [10]:
#cap = cv2.VideoCapture('https://student:zumi2020@keuper-labs.org/zumi-cam')
#ret,frame = cap.read() 
#pic2 = frame

In [6]:
%%time
datadiff=pic1-pic2

Wall time: 2.99 ms


In [7]:
%%time
posi=[]
posj=[]
count=0
for i in range(173,940):
    for j in range(261,1298):
        if((datadiff[i][j][0]>60) and (datadiff[i][j][0]<200) or (datadiff[i][j][1]>70) and (datadiff[i][j][1]<200) or (datadiff[i][j][2]>70) and (datadiff[i][j][2]<200)):
            #print(datadiff[i][j])
            #print(i)
            posi.append(i)
            posj.append(j)
            count=count+1
            #print(j)
count

Wall time: 5.03 s


1488

In [ ]:
import cv2
cap = cv2.VideoCapture('https://student:zumi2020@keuper-labs.org/zumi-cam')
ret,frame = cap.read() # return a single frame in variable `frame`
frame=pic2
while True:
    drawcirclekmeans(frame,datadiff,posi,posj,pic2)
    gencoordinates(400,400,frame)
    cv2.imshow("Frame", frame)
    key = cv2.waitKey(1)
    if key == 27 & 0xff == ord('q'):
        break

In [8]:
def drawcircle(frame,datadiff,posi,posj,pic2):
    i = 300
    while(i<=len(posi)):
        c1=int(pic2[posi[i]][posj[i]][0])
        c2=int(pic2[posi[i]][posj[i]][1])
        c3=int(pic2[posi[i]][posj[i]][2])
        putCoord(posj[i],posi[i],frame)
        cv2.circle(frame, (posj[i],posi[i]), 5, (c1,c2,c3),10,8,0)
        i=i+700
    return frame

def drawcirclekmeans(frame,datadiff,posi,posj,pic2):
    s = [[posj[y],posi[y]] for y in range(len(posi))]
    from sklearn.cluster import KMeans
    import numpy as np
    kmeans = KMeans(n_clusters=2, random_state=0).fit(s)
    kmeans.labels_
    kmeans.cluster_centers_
    for n in range(len(kmeans.cluster_centers_)):
        putCoord(int(kmeans.cluster_centers_[n][0]),int(kmeans.cluster_centers_[n][1]),frame)
        cv2.circle(frame, (int(kmeans.cluster_centers_[n][0]),int(kmeans.cluster_centers_[n][1])), 5, (255,0,0),10,8,0)
    return frame

def drawrect(frame,datadiff,posi,posj):
    cv2.rectangle(frame,(posj[5],posi[5]),(posj[700],posi[700]),1,8,0)
    return frame
    
    
def gencoordinates(x,y,frame):
    cv2.putText(frame, "0,0", (x-20, y+20), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 0, 255), 2)
    cv2.circle(frame, (x,y), 5, (255,0,0),10,8,0)
    cv2.line(frame, (x,0), (x,1440), (255,0,0),1,8,0) 
    i = int(x/50)
    for j in range(i):
        cv2.putText(frame, "-"+str((j+1)*50), (x-((j+1)*50),y+20), cv2.FONT_HERSHEY_SIMPLEX, 0.2, (0, 0, 255), 1)
        cv2.circle(frame, (x-((j+1)*50),y), 1, (255,0,0),2,8,0)
    i = int(480-x/50)
    for j in range(i):
        cv2.putText(frame, ""+str((j+1)*50), (x+((j+1)*50),y+20), cv2.FONT_HERSHEY_SIMPLEX, 0.2, (0, 0, 255), 1)
        cv2.circle(frame, (x+((j+1)*50),y), 1, (255,0,0),2,8,0)
    i = int(y/50)
    for j in range(i):
        cv2.putText(frame, "-"+str((j+1)*50), (x-20,y+((j+1)*50)), cv2.FONT_HERSHEY_SIMPLEX, 0.2, (0, 0, 255), 1)
        cv2.circle(frame, (x,y-((j+1)*50)), 1, (255,0,0),2,8,0)
    i = int(640-y/50)
    for j in range(i):
        cv2.putText(frame, ""+str((j+1)*50), (x-20,y-((j+1)*50)), cv2.FONT_HERSHEY_SIMPLEX, 0.2, (0, 0, 255), 1)
        cv2.circle(frame, (x,y+((j+1)*50)), 1, (255,0,0),2,8,0)
   
    cv2.line(frame, (0,y), (1440,y), (255,0,0),1,8,0) 
    return frame

def putCoord(x,y,frame):
    newX=x-400
    newY=(y-400)*(-1)
    c=str(newX)+","+str(newY)
    #print(c)
    cv2.putText(frame, c, (x-15, y-15), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 0, 255), 2)
    return
        

In [9]:
count=0
for i in range(173,940):
    count=count +1 
count

767

In [10]:
s = [[posj[y],posi[y]] for y in range(len(posi))]
from sklearn.cluster import KMeans
import numpy as np
kmeans = KMeans(n_clusters=2, random_state=0).fit(s)
kmeans.labels_
kmeans.cluster_centers_

array([[1111.89140271,  638.21266968],
       [1173.91390728,  812.01655629]])

In [14]:
from PIL import Image
from numpy import asarray
# load the image
image = Image.open('test.png')
# convert image to numpy array
test = asarray(image)
print(type(test))
# summarize shape
print(test.shape)

<class 'numpy.ndarray'>
(1080, 1440, 3)
None


In [46]:
def getzumiblue(frame,kmeans):
    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    mask = cv2.imread("top_view.png", 0)
    hsv_frame = cv2.bitwise_and(hsv_frame, hsv_frame, mask=mask)
    low_blue = np.array([109, 146, 56])
    high_blue = np.array([121, 176, 101])
    blue_mask = cv2.inRange(hsv_frame, low_blue, high_blue)
    coord=cv2.findNonZero(blue_mask)
    for i in range (len(coord)):
        positionx = coord[i][0][0]
        positiony = coord[i][0][1]
        trueposx = kmeans[1][0]
        trueposy = kmeans[1][1]
        trueposx1 = kmeans[0][0]
        trueposy1 = kmeans[0][1]
        if(abs(positionx-trueposx)<10 and abs(positiony-trueposy)<10):
            trueposx=trueposx-400
            trueposy=(trueposy-400)*(-1)
            return trueposx,trueposy
        if(abs(positionx-trueposx1)<10 and abs(positiony-trueposy1)<10):
            trueposx1=trueposx1-400
            trueposy1=(trueposy1-400)*(-1)
            return trueposx1,trueposy1

In [47]:
def getzumiyellow(frame,kmeans):
    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    mask = cv2.imread("top_view.png", 0)
    hsv_frame = cv2.bitwise_and(hsv_frame, hsv_frame, mask=mask)
    low_yellow = np.array([18, 135, 142])
    high_yellow = np.array([25, 190, 210])
    yellow_mask = cv2.inRange(hsv_frame, low_yellow, high_yellow)
    coord=cv2.findNonZero(yellow_mask)
    for i in range (len(coord)):
        positionx = coord[i][0][0]
        positiony = coord[i][0][1]
        trueposx = kmeans[1][0]
        trueposy = kmeans[1][1]
        trueposx1 = kmeans[0][0]
        trueposy1 = kmeans[0][1]
        if(abs(positionx-trueposx)<10 and abs(positiony-trueposy)<10):
            trueposx=trueposx-400
            trueposy=(trueposy-400)*(-1)
            return trueposx,trueposy
        if(abs(positionx-trueposx1)<10 and abs(positiony-trueposy1)<10):
            trueposx1=trueposx1-400
            trueposy1=(trueposy1-400)*(-1)
            return trueposx1,trueposy1

In [48]:
def getzumired(frame,kmeans):
    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    mask = cv2.imread("top_view.png", 0)
    hsv_frame = cv2.bitwise_and(hsv_frame, hsv_frame, mask=mask)
    low_red = np.array([0, 142, 51])
    high_red = np.array([11, 255, 178])
    red_mask = cv2.inRange(hsv_frame, low_red, high_red)
    coord=cv2.findNonZero(red_mask)
    for i in range (len(coord)):
        positionx = coord[i][0][0]
        positiony = coord[i][0][1]
        trueposx = kmeans[1][0]
        trueposy = kmeans[1][1]
        trueposx1 = kmeans[0][0]
        trueposy1 = kmeans[0][1]
        if(abs(positionx-trueposx)<10 and abs(positiony-trueposy)<10):
            trueposx=trueposx-400
            trueposy=(trueposy-400)*(-1)
            return trueposx,trueposy
        if(abs(positionx-trueposx1)<10 and abs(positiony-trueposy1)<10):
            trueposx1=trueposx1-400
            trueposy1=(trueposy1-400)*(-1)
            return trueposx1,trueposy1

In [45]:
zumired = getzumired(test,kmeans.cluster_centers_)
zumiblue = getzumiblue(test,kmeans.cluster_centers_)

print(zumired)
print(zumiblue)

(711.8914027149322, -238.21266968325813)
(773.9139072847681, -412.016556291391)
